[[eval]]
env_id = "math500"
num_examples = -1
rollouts_per_example = 1

[[eval]]
env_id = "aime2024"
num_examples = -1
rollouts_per_example = 8

[[eval]]
env_id = "gpqa"
num_examples = -1
rollouts_per_example = 1

[[eval]]
env_id = "livecodebench"
num_examples = -1
rollouts_per_example = 1
max_concurrent = 16 # to limit sandbox usage