model = "Qwen/Qwen3-30B-A3B-Instruct-2507"
max_steps = 100
batch_size = 256
rollouts_per_example = 8

[sampling]
max_tokens = 512

[[env]]
id = "primeintellect/gsm8k"

[wandb]
project = "gsm8k"
name = "qwen3-30b-i-gsm8k"