model = "Qwen/Qwen3-30B-A3B-Instruct-2507"
max_steps = 100
batch_size = 256
rollouts_per_example = 8

[sampling]
max_tokens = 512

[[env]]
id = "primeintellect/wiki-search"

[wandb]
project = "wiki-search"
name = "qwen3-30b-i-wiki-search"