model = "Qwen/Qwen3-30B-A3B-Thinking-2507"
max_steps = 100
batch_size = 256
rollouts_per_example = 8

[sampling]
max_tokens = 4096

[[env]]
id = "primeintellect/wordle"

[wandb]
project = "wordle"
name = "qwen3-30b-t-wordle"